version: "3"
services:
  benthos:
    image: jeffail/benthos:4.0.0-rc3
    volumes:
      - ./conf/benthos.yaml:/benthos.yaml
    links:
      - rabbit
  rabbit:
    image: rabbitmq:3.9.14
    volumes:
      - ./conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./conf/definitions.json:/etc/rabbitmq/definitions.json
  stream:
    image: stream_transport:latest
    volumes:
      - ./data:/data
    links:
      - rabbit
