version: "3.9"
services:
  benthos:
    image: jeffail/benthos:4.0.0-rc3
    volumes:
      - ./conf/benthos.yaml:/benthos.yaml
    links:
      - rabbit
  rabbit:
    image: rabbitmq:3.9.14
    volumes:
      - ./conf/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./conf/definitions.json:/etc/rabbitmq/definitions.json
    ports:
      - 5672:5672  # TODO test only, uncomment this in the final version
